---
title: "Appendix A"
header-includes:
- \usepackage{pdflscape}
- \newcommand{\blandscape}{\begin{landscape}}
- \newcommand{\elandscape}{\end{landscape}}
author: "Greg Barnsley"
date: "`r format(Sys.time(), '%d %B, %Y, %H:%M')`"
output: pdf_document
bibliography: references.bib
csl: vancouver-imperial-college-london.csl
---

\blandscape

# Model Parameters

```{r, include = FALSE}
#automatically get some of the model parameters
#example_fits <- readRDS("countryfits.Rds")[["GBR"]]
example_fits <- readRDS("C:/Users/gbarnsle/Documents/Covid Vaccine Impact/global-lmic-reports-orderly/archive/excess_mortality/20210929-172356-9c02a617/res.rds")

#extract parameters
generated_params <- data.frame(
  Parameter = c("Number of Initial Infections",
                "Mean Incubation Period",
                "Mean Period of Natural Immunity",
                "Mean Duration of a Mild Infection",
                "Mean Duration of a Hospitalised Infection",
                "Mean Duration of Treatment with Oxygen,\ngiven that they survive",
                "Mean Duration of Treatment with Oxygen,\ngiven that they die",
                "Mean Duration of Treatment without Oxygen,\ngiven that they survive",
                "Mean Duration of Treatment without Oxygen,\ngiven that they die",
                "Mean Duration of Treatment with Ventilation,\ngiven that they survive",
                "Mean Duration of Treatment with Ventilation,\ngiven that they die",
                "Mean Duration of Treatment without Ventilation,\ngiven that they survive",
                "Mean Duration of Treatment without Ventilation,\ngiven that they die",
                "Mean Duration of recovery post-Ventilation",
                "Probability of Death, Non-Severe, No Treatment",
                "Probability of Death, Severe, No Treatment"),
  Value = c(
    sum(example_fits$parameters$seeding_cases),
    example_fits$parameters$dur_E,
    example_fits$parameters$dur_R,
    example_fits$parameters$dur_IMild,
    example_fits$parameters$dur_ICase,
    example_fits$parameters$dur_get_ox_survive,
    example_fits$parameters$dur_get_ox_die,
    example_fits$parameters$dur_not_get_ox_survive,
    example_fits$parameters$dur_not_get_ox_die,
    example_fits$parameters$dur_get_mv_survive,
    example_fits$parameters$dur_get_mv_die,
    example_fits$parameters$dur_not_get_mv_survive,
    example_fits$parameters$dur_not_get_mv_die,
    example_fits$parameters$dur_rec,
    paste0(unique(example_fits$parameters$prob_non_severe_death_no_treatment)*100,"%"),
    paste0(unique(example_fits$parameters$prob_severe_death_no_treatment)*100,"%")
  ),
  Description = c(
    "Number of cases to start the epidemic, randomly assigned to age groups.",
    "How long from exposure to the disease to becoming infectious.",
    "How long until aquired immunity wane?.",
    "For a mild/asymptomatic case how long until recovery.",
    "How long until entry to hospital for a severe case.",
    "These parameters inform the time spent in Hospital or ICU",
    "See above",
    "See above",
    "See above",
    "See above",
    "See above",
    "See above",
    "See above",
    "See above",
    "Probability of death in non-severe cases that require hospitalisation and have not recieved treatement.",
    "Probability of death in severe cases that have not recieved treatement."
  ),
  Source = c("-",
             "@incubation",
             "@nat_immune_duration",
             "@gen_time",
             "@gen_time",
             "@sreevalsan2020estimation @haw2020epidemiological\n@hawryluk2020inference @oliveira2021icu",
             "@sreevalsan2020estimation @haw2020epidemiological\n@hawryluk2020inference @oliveira2021icu",
             "-",
             "-",
             "@pritchard2020isaric",
             "ICNARC COVID Report",
             "-",
             "-",
             "-",
             "-",
             "-"),
  category = "di1"
) %>%
  rbind(
    data.frame(
  Parameter = c("Mean Period of Vaccine Protection",
                "Relative Infectiousness of Vaccinated",
                "Mean Period to vaccine protection"),
  Value = c(example_fits$parameters$dur_V,
            paste0(unique(example_fits$parameters$rel_infectiousness_vaccinated)*100, "%"),
            example_fits$parameters$dur_vaccine_delay),
  Description = c("How long until vaccine protection (both types) wanes",
                  "If a vaccinated person is infected how does their infectiousness compare to the unvaccinated",
                  "Duration from vaccination to development of protection (both types)"),
  Source = c("-",
             "-",
             "-"),
  category = "v1"
)
  ) %>%
  rbind(
    data.frame(
      Parameter = c(
        "Duration of the Delta Variant Shift",
        "Delta Variant increase in probability of hospitalisation",
        "Delta Variant immune escape percentage",
        "Vaccine Effectiveness Infection-single dose,\nagainst Delta Variant",
        "Vaccine Effectiveness Infection-two doses,\nagainst Delta Variant",
        "Vaccine Effectiveness Disease-single dose,\nagainst Delta Variant",
        "Vaccine Effectiveness Disease-two doses,\nagainst Delta Variant"
      ),
    Value = c(
      example_fits$interventions$delta_adjustments$shift_duration,
      paste0((example_fits$interventions$delta_adjustments$prob_hosp_multiplier-1)*100, "%"),
      paste0(example_fits$interventions$delta_adjustments$immune_escape*100, "%"),
      paste0(example_fits$interventions$delta_adjustments$ve_i_low_d*100, "%"),
      paste0(example_fits$interventions$delta_adjustments$ve_i_high_d*100, "%"),
      paste0(example_fits$interventions$delta_adjustments$ve_d_low_d*100, "%"),
      paste0(example_fits$interventions$delta_adjustments$ve_d_high*100, "%")
    ),
    Description = c(
      "The time from the Delta variant's introduction to the country to becoming the dominant strain of COVID-19.",
      "The relative increase in probability of hospitalisation for people infected with the Delta variant.",
      "The percentage of people previously infected with a non-Delta variant, who would not have become susceptible to re-infection with the non-Delta variants over the shift period, who will be susceptible to being re-infected with the Delta variant.",
      "Reduced vaccine effectiveness for the Delta variant.",
      "See above.",
      "See above.",
      "See above."
    ),
    Source = c(
      "-",
      "@prob_hosp_delta",
      "-",
      "-",
      "-",
      "-",
      "-"
    ),
    category = "d1"
    )
    )

#write the manuall parameters
manual_params <- data.frame(
  Parameter = c(
    "Vaccine Effectiveness against Infection",
    "Vaccine Effectiveness Infection-single dose",
    "Vaccine Effectiveness Infection-two doses",
    "Vaccine Effectiveness against Severe Disease",
    "Vaccine Effectiveness Disease-single dose",
    "Vaccine Effectiveness Disease-two doses",
    "Vaccines Available",
    "Vaccine Strategy",
    "Vaccine Uptake"
  ),
  Value = c(
    "Variable over time",
    "60%",
    "80%",
    "Variable over time",
    "80%",
    "98%",
    "Variable over time and country",
    "HCW & High-risk, then age ordered",
    "80%"
  ),
  Description = c(
    "To simulate a multidose vaccine, this value scales between a higher estimate (Vaccine Effectiveness Infection-two doses) and a lower estimate (Vaccine Effectiveness Infection-single dose), based on the ratio of people fully vaccinated to single dose. Modelled as a reduction in rate of infection. Values chosen to be representative of all vaccines.",
    "See Above",
    "See Above",
    "To simulate a multidose vaccine, this value scales between a higher estimate (Vaccine Effectiveness Disease-two doses) and a lower estimate (Vaccine Effectiveness Disease-single dose), based on the ratio of people fully vaccinated to single dose. Modelled as a reduction in probability of hospitalisation. Values chosen to be representative of all vaccines.",
    "See Above",
    "See Above",
    "Dervied from the reported number of vaccinations each day from Our World in Data and the WHO.",
    "A general assumption made about the prioritisation of vaccines, aligns with WHO guidance.",
    "The cap on the number of people in each age-group who will become vaccinated, simulates a level of vaccine hesitancy."
  ),
  Source = c(
    "-",
    "SPI-M-O Roadmap 3",
    "SPI-M-O Roadmap 3",
    "-",
    "SPI-M-O Roadmap 3",
    "SPI-M-O Roadmap 3",
    "@OWID-Vaccines @who_dash",
    "-",
    "-"
  ),
  category = "v1"
) %>%
  rbind(
    data.frame(
      Parameter = c(
        "ICU & Hospital bed capacity",
        "Contact Matrix"
  ),
  Value = c(
    "Variable over country",
    "Variable over country"
  ),
  Description = c(
    "Data used where possible and esimated with a boosted regression tree otherwise",
    "Age-specific contact patterns estimated from social contact surverys and chosen based on income group status"
  ),
  Source = c(
    "@report12",
    "@report12"
  ),
  category = "c1"
    )
    ) %>%
  rbind(
    data.frame(
      Parameter = c(
        "Probability of Death, Non-Severe,\nwith treatment",
        "Probability of Death, Severe,\nwith treatment",
        "Probability of Hospitalisation",
        "Probability of Developing Severe Symptoms"
  ),
  Value = c(
    "Variable over age",
    "Variable over age",
    "Variable over age",
    "Variable over age"
  ),
  Description = c(
    "Probability of death in non-severe cases that require hospitalisation and have recieved treatement.",
    "Probability of death in severe cases that have recieved treatement.",
    "Baseline probability of hospitalisation for vaccinated and non-vaccinated people.",
    "For those that are hospitalised, what is the probability of developing severe symptoms."
  ),
  Source = c(
    "@ifr",
    "@ifr",
    "@prob_hosp_ref",
    "@prob_hosp_ref"
  ),
  category = "di1"
    )
    )%>%
  rbind(
    data.frame(
      Parameter = c(
        "Start date for Delta Shift"
      ),
    Value = c(
      "Variable over Country"
    ),
    Description = c(
      "Derived from the point at which over 10% of COVID-19 isolates are of the Delta variant."
    ),
    Source = c(
      "@covariants @gsaid"
    ),
    category = "d1"
    )
    )

#titles data frame
titles_df <- data.frame(
  Parameter = c(
    "Country Specific Parameters:",
    "Disease Related Parameters:",
    "Delta Adjustment Parameters:",
    "Vaccine Related Parameters:"
  ),
  Value = "",
  Description = "",
  Source = "",
  category = c(
    "c0",
    "di0",
    "d0",
    "v0"
  )
)

table_params <- rbind(generated_params, manual_params, titles_df) %>%
  arrange(category) %>%
  select(!category) %>% #text wrap
  mutate(
    Description = sapply(lapply(Description, strwrap, width=50), paste, collapse="\n")
  )

#get which ones should be italics
bold <- which(table_params$Value == "")

```

```{r, include = FALSE}
#adjustments to what I want to use
table_params[table_params$Parameter=="Delta Variant immune escape percentage",] <- 
  c("Delta Variant immune escape percentage",
    "61.3%",
    "Percentage of those previously infected with a non-delta variant who would 
    be susceptible to the Delta variant. Taken from a modelling estimate of 
    immune escape for the Beta variant, which has a similar reduction in 
    neutralising antibodies to the Delta variant.",
    "@delta_beta_antibodies @immune_modelling")

table_params[table_params$Parameter %in% c(
  "Vaccine Effectiveness Disease-single dose,\nagainst Delta Variant",
  "Vaccine Effectiveness Disease-two doses,\nagainst Delta Variant"),c("Value", "Source")] <- 
  matrix(c("75%", "PHE Vaccine Effectiveness against Hospitalisation preprint",
           "94%", "PHE Vaccine Effectiveness against Hospitalisation preprint"), byrow = TRUE,
         nrow = 2)

table_params[table_params$Parameter %in% c(
  "Vaccine Effectiveness Infection-single dose,\nagainst Delta Variant",
  "Vaccine Effectiveness Infection-two doses,\nagainst Delta Variant"),c("Value", "Source")] <- 
  matrix(c("22.4%", "@vacc_eff_inf_delta",
           "64.6%", "@vacc_eff_inf_delta"), byrow = TRUE,
         nrow = 2)

table_params[table_params$Parameter == "Mean Period of Vaccine Protection",] <-
  c("Mean Period of Vaccine Protection", 
    "446", 
    "How long until vaccine protection (both types) wanes. Roughly calculated 
    from the time to 50% efficacy (150 days) from 70%, so that by that time 30% of those 
    vaccinated have returned to being susceptible.",
    "@vaccine_waning")

```


```{r, echo=FALSE, fig.cap = "Fixed model parameters with explainations"}
set_flextable_defaults(fonts_ignore=TRUE)
FitFlextableToPage <- function(ft, pgwidth = 8){

  ft_out <- ft %>% autofit()

  ft_out <- width(ft_out, width = dim(ft_out)$widths*pgwidth /(flextable_dim(ft_out)$widths))
  return(ft_out)
}
table_params %>%
  flextable() %>%
  colformat_md() %>%
  FitFlextableToPage() %>% 
  bold(i = bold) %>% 
  bold(part = "header") %>% 
  align(j = 2, align = "right")
```

\elandscape

<!-- # MCMC Parameters -->

<!-- # Sensitivity Analysis -->

<!-- # Isolate Pre-Epidemic Deaths -->
