---
title: "The Global Impact of COVID-19 Vaccinations: A model fitting based approach"
author: "Greg Barnsley"
date: "`r format(Sys.time(), '%d %B, %Y, %H:%M')`"
output: html_document
bibliography: references.bib
csl: vancouver-imperial-college-london.csl
---

# Introduction

Write later

# Methods

## Data Sources

We used reported excess mortality data from the Economist excess mortality 
model [@econ-excess-model]. This draws reported excess mortality from the World 
Mortality Dataset [@world_mortality] and reported COVID-19 related deaths from 
@JHU. For countries that do not report excess mortality data for the period of
January 2020 onwards, the model predicts a an estimate of the excess mortality 
per day of each missing week. These are made via a boosted regression tree 
approach with agboost [@agtboost] and takes a variety of economic [@WDI], 
political [@vdem; @bindem; @freehouse; @oxgrt; @google_mob], 
serological [@serotracker], geographic [@maps; @DVN-SPHS5E_2010; @CEPII-2011-25], 
and health related data [@JHU; @OWID-Vaccines; @OWID-Testing; @Liun415; 
@who_malaria; @who_tb; @who_gho] as covariates.

Additional data sources used to parameterise our models vaccinations were taken 
from @OWID-Vaccines and @who_dash. STUFF ABOUT vaccine EFFICACY

We characterised our adjustments for the delta variant of COVID-19 using variant
sequence data from @covariants, as well as estimates of the variants relative
effect on hospitalisation rates in comparison to the alpha variant from 
@prob_hosp_delta. Estimates for the the vaccines effectiveness against disease and 
infection with the delta variant were taken from estimates of their efficacy in
@vaccine_efficacy_delta. Additionally, with no studies looking at delta 
re-infection rates for those infected with a previous variant of COVID-19, an 
escape percentage of 46% was inferred from @immune_escape_delta. THINK AVOUT THIS SOME MORE!!!!!

## Vaccine Effectiveness Modelling

We used a previously developed mathematical model for SARS-CoV-2 transmission 
and vaccination [@nimue]. The age-structured deterministic SEIR-type 
compartmental model incorporates an age specific probability of infection 
determined by age-based contact matrices (WHERE FROM) as well as the disease clinical 
pathway, which includes hospitalisation, oxygen support and intensive care 
needs. Vaccination is modelled as an additional dimension disaggregating the 
population into those who have not received the vaccine, have received the 
vaccine but are not yet protected, have received the vaccine and are protected 
and those who have received the vaccine but are no-longer protected. In this 
model only those who are currently infected do not receive the vaccine. 
Vaccine protection is modelled in a two-step process with protection against
infection and protection against disease (a reduction in rate of hospitalisation
and death for the infected). Additionally this model includes the loss of 
naturally-acquired infections.

In this set-up we assume that all countries follow the same vaccination 
strategy, first health-care workers and high-risk groups (represented by a 
proportion of of the working aged population) then descending through age groups
as the vaccination progresses, until all groups over the age of 18 are included.
We assume that up to 80% of each group will become vaccinated to represent a 
form of vaccine hesitancy. To simulate two dose vaccines, we scale the levels of
vaccine protection between estimates for a single dose and estimates for a 
double dose based on a derived ratio between those with one vaccination and 
those with both.

We applied adjustments to this model to account for the dominance of the Delta
variant (SOURCE) with worse outcomes (SOURCE), reduced vaccine efficacy (SOURCE),
and immune escape. This was incorporated by allowing the relevant parameters to
scale over a 60 day period from their pre-delta to their post-delta values. 
During this time the rate of loss of natural immunity was increased so that 46% 
of those in who would be recovered transfer to the susceptible compartment (THIS NEEDS MORE WORK).
The date on which to start this transition was determined by the first date
at which over 10% of the countries sequences were of the Delta variant. For 
countries with no sequence data, we used the median date of countries in their
UN sub-region or continent if those were missing too.

## Model Fitting

We adjusted a previous approach [@syria-fitting] to fit to the excess mortality
data. We assume the likelihood of the model's simulated deaths, $D_w$ over a 
week, $w$, are related to the reported or estimated excess mortality for that 
week, $M_w$, by the negative binomial distribution, so that,

$$
M_w \sim \mathrm{NB}(2, \frac{2}{2 + D_w}) \leftrightarrow L(M_w|D_w) = 
{M_w + 2 -1 \choose M_w} \times \left(1-\frac{2}{2 + D_w}\right)^2 \times
\left(\frac{2}{2 + D_w}\right)^{M_w}.
$$

This allows the mean of the negative binomial distribution to be $D_w$.

We set our transmission parameters according to an effective reproduction number,
$R_t$, that varys over time. For some time, $x$, in days from the first death
of the epidemic, we let:

$$
R_t(x) = R_0 \times f(-\sum_{i = 1}^{\lceil (x - 10)/14 \rceil} R_w_i),
$$

where $R_0$ is the basic reproduction number and $R_w_i$ represents a change in 
non-vaccine interventions or mobility that effects the reproduction of COVID-19.
These effects are added every 14 days, starting from 10 days before the first 
death of the epidemic. We fit our model with a Bayseian approach by allowing the
start date, $R_0$, and $\bold{R_w}$ to vary and using a metropolis-Hastings 
within Gibbs Monte Carlo markov-chain to sample from the posterior distribution 
of these parameters.

## Counter-factual Modelling

The baseline, vaccine-less, and COVAX counterfactuals were simulated by drawing parameters from the fits, adjusting the availability of vaccines and running the model with these parameters. Any comparisons between counterfactuals were made between replicates from identical parameters first and then calculating the summary measures from these. For comparisons across countries random combinations of replicates were chosen. Estimates of the number of lives saved by direct and indirect vaccine effects were made by simulating a counterfactual with the baseline number of vaccinations but with no protection against infection.



# Results

# Dicussion

bit about uncertainty in estimates

rt effected by presence of vaccine etc

# Bibilography

